coverage_service: cobertura_xml
xcodeproj: ADNParqueadero/ADNParqueadero.xcodeproj
scheme: ADNParqueadero
configuration: TestedConfiguration
source_directory: ADNParqueadero/ADNParquedero.xcworkspace
output_directory: ./
ignore:
  - ADNParqueaderoUITest/*
  - ADNParqueaderoTest/*
