coverage_service: cobertura_xml
xcodeproj: path/to/ADNParqueadero.xcodeproj
scheme: ADNParqueadero
configuration: TestedConfiguration
source_directory: path/to/sources/to/include
output_directory: ./
ignore:
  - ADNParqueaderoUITest/*
  - ADNParqueaderoTest/*
