pipeline {
  agent any
  stages {
    stage('Cancel previous build') {
      steps {
        milestone label: '', ordinal:  Integer.parseInt(env.BUILD_ID) - 1
        milestone label: '', ordinal:  Integer.parseInt(env.BUILD_ID)
      }
    }
    stage('Compile') {
      steps {
        echo "------------>Compile<------------"
        sh 'pod install' // Esta instrucción puede variar dependiendo del gestor de paquetes.
        sh 'xcodebuild -scheme [ADNParqueadero] clean build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO"'
      }
    }
    stage('Unit Tests') {
      steps{
        echo "------------>Unit Tests<------------"
        sh 'xcodebuild test -scheme [ADNParqueaderoTest] -configuration "Debug"  -destination "platform=iOS Simulator,name=[iPhone 12 Pro],OS=[iOS 14.5]"'
      }
    }
    stage('Static Code Analysis') {
      steps{
        echo '------------>Análisis de código estático<------------'
        sh 'run-sonar-swift.sh -v'
        withSonarQubeEnv('Sonar') {
          sh "${tool name: 'SonarScanner-Mac', type:'hudson.plugins.sonar.SonarRunnerInstallation'}/bin/sonar-scanner"
        }
      }
    }
    stage('Clean workplace') {
      steps {
        deleteDir()
      }
    }
  }
  post {
    failure {
      echo 'This will run only if failed'
      mail (to: 'jaime.uribe@ceiba.com.co',subject: "Failed Pipeline:${currentBuild.fullDisplayName}",body: "Something is wrong with ${env.BUILD_URL}")
    }
  }
}