pipeline {
  agent any
  stages {
    stage('Cancel previous build') {
      steps {
        milestone label: '', ordinal:  Integer.parseInt(env.BUILD_ID) - 1
        milestone label: '', ordinal:  Integer.parseInt(env.BUILD_ID)
      }
    }
    stage('Compile') {
      steps {
        echo "------------>Compile<------------"
        #sh 'pod install' // Esta instrucción puede variar dependiendo del gestor de paquetes.
        sh 'xcodebuild -scheme [ADNParqueadero] clean build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO"'
      }
    }
    stage('Unit Tests') {
      steps{
        echo "------------>Unit Tests<------------"
        sh 'xcodebuild test -scheme [ADNParqueaderoTest] -configuration "Debug"  -destination "platform=iOS Simulator,name=[iPhone 12 Pro],OS=[iOS 14.5]"'
      }
    }
    stage('Clean workplace') {
      steps {
        deleteDir()
      }
    }
  }
}